// Generated by JobsMarket. It holds only the profile text you approved and is read by panel.js.
export const PLAN = {
 "version": 2,
 "owner": "Jordan Avery",
 "profileUrl": "https://www.linkedin.com/in/jordan-avery-example/",
 "createdAt": "2026-10-06T00:00:00.000Z",
 "steps": [
  {
   "id": "headline",
   "group": "Top of profile",
   "title": "Headline",
   "open": "https://www.linkedin.com/in/jordan-avery-example/edit/intro/",
   "hint": "Your intro form opens. Press Fill, check the headline, then press Save. If the form does not open, click the pencil on your intro card first.",
   "fields": [
    {
     "labels": [
      "Headline"
     ],
     "text": "Reporting Analyst | SQL, Power BI and Excel | Telecom and logistics reporting | Melbourne"
    }
   ]
  },
  {
   "id": "about",
   "group": "Top of profile",
   "title": "About",
   "open": "https://www.linkedin.com/in/jordan-avery-example/edit/about/",
   "hint": "Your About form opens. Press Fill, check it, then press Save. If the form does not open, click the pencil on About first. Add the top skills in the same form, one at a time.",
   "fields": [
    {
     "labels": [
      "About",
      "Summary",
      "Description"
     ],
     "text": "I build the dashboards and month end reports that regional managers use to track churn and retention, and I check the data before anyone makes a decision with it.\n\nAt Northwind Telecom I built 14 Power BI dashboards and rewrote the month end SQL scripts, cutting report preparation from three days to four hours. At Harbourline Logistics I automated 22 weekly Excel reports with Python.\n\nI'm open to reporting and data analyst roles in Melbourne.",
     "fallbackFirstTextarea": true
    }
   ],
   "copy": [
    {
     "label": "Top skills",
     "text": "SQL\nMicrosoft Power BI\nMicrosoft Excel\nPython (Programming Language)\nData Validation"
    }
   ]
  },
  {
   "id": "exp-northwind-telecom-senior-reporting-analy",
   "group": "Experience",
   "title": "Northwind Telecom, Senior Reporting Analyst",
   "open": "https://www.linkedin.com/in/jordan-avery-example/details/experience/",
   "hint": "Click the pencil next to Senior Reporting Analyst (Mar 2022 to Present) at Northwind Telecom. When the form is open, press Fill. Only the description changes. Check it, then press Save on LinkedIn.",
   "guard": [
    {
     "labels": [
      "Title"
     ],
     "equals": "Senior Reporting Analyst"
    }
   ],
   "fields": [
    {
     "labels": [
      "Description"
     ],
     "text": "• Built 14 Power BI dashboards that regional managers use to track churn and retention.\n• Rewrote the month end SQL scripts and cut report preparation from three days to four hours.\n• Trained six analysts in data validation and version control."
    }
   ]
  },
  {
   "id": "exp-harbourline-logistics-data-analyst",
   "group": "Experience",
   "title": "Harbourline Logistics, Data Analyst",
   "open": "https://www.linkedin.com/in/jordan-avery-example/details/experience/",
   "hint": "Click the pencil next to Data Analyst (Jul 2019 to Feb 2022) at Harbourline Logistics. When the form is open, press Fill. Only the description changes. Check it, then press Save on LinkedIn.",
   "guard": [
    {
     "labels": [
      "Title"
     ],
     "equals": "Data Analyst"
    }
   ],
   "fields": [
    {
     "labels": [
      "Description"
     ],
     "text": "• Automated 22 weekly Excel reports with Python, saving the team about 12 hours each week.\n• Designed a SQL data model for delivery times across 9 depots."
    }
   ]
  },
  {
   "id": "proj-churn-early-warning",
   "group": "Projects",
   "title": "Churn Early Warning",
   "open": "https://www.linkedin.com/in/jordan-avery-example/details/projects/",
   "hint": "Click the pencil next to Churn Early Warning. Press Fill. It replaces the description. It also sets the end date to June 2025. Check it, then press Save.",
   "guard": [
    {
     "labels": [
      "Project name",
      "Name"
     ],
     "equals": "Churn Early Warning"
    }
   ],
   "fields": [
    {
     "labels": [
      "Description"
     ],
     "text": "A Power BI report that flags accounts likely to churn, built from billing and support data."
    }
   ],
   "checks": [
    {
     "labels": [
      "I am currently working on this project",
      "I am currently working on this"
     ],
     "checked": false
    }
   ],
   "selects": [
    {
     "scope": "End date",
     "option": "June"
    },
    {
     "scope": "End date",
     "option": "2025"
    }
   ]
  },
  {
   "id": "edu-eastlake-university",
   "group": "Education",
   "title": "Eastlake University",
   "open": "https://www.linkedin.com/in/jordan-avery-example/details/education/",
   "hint": "Click the pencil next to Eastlake University. Press Fill. It adds the text under the description and keeps the rest. Check it, then press Save.",
   "guard": [
    {
     "labels": [
      "School"
     ],
     "contains": "Eastlake University"
    }
   ],
   "fields": [
    {
     "labels": [
      "Description"
     ],
     "text": "Capstone on retail demand forecasting in Python.",
     "append": true
    }
   ]
  },
  {
   "id": "cert-power-bi-data-analyst-associate",
   "group": "Certifications",
   "title": "Power BI Data Analyst Associate",
   "open": "https://www.linkedin.com/in/jordan-avery-example/details/certifications/",
   "hint": "Click + to add a certification. Press Fill. Then pick Microsoft from the suggestions under Issuing organization, check the date, and press Save. Turn off sharing with your network first if you do not want a post about it.",
   "guard": [
    {
     "labels": [
      "Name"
     ],
     "emptyOr": "Power BI Data Analyst Associate"
    }
   ],
   "fields": [
    {
     "labels": [
      "Name"
     ],
     "text": "Power BI Data Analyst Associate"
    },
    {
     "labels": [
      "Issuing organization",
      "Issuing organisation"
     ],
     "text": "Microsoft"
    }
   ],
   "selects": [
    {
     "scope": "Issue date",
     "option": "March"
    },
    {
     "scope": "Issue date",
     "option": "2024"
    }
   ]
  },
  {
   "id": "skills",
   "group": "Skills",
   "title": "Skills",
   "open": "https://www.linkedin.com/in/jordan-avery-example/details/skills/",
   "hint": "Click + to add a skill. Press Fill next skill, pick the matching suggestion, press Save, and repeat. Press Skip for any you already have.",
   "skillList": [
    "SQL",
    "Microsoft Power BI",
    "Microsoft Excel",
    "Python (Programming Language)",
    "Tableau",
    "Data Validation",
    "Stakeholder Reporting",
    "Dashboard Design"
   ]
  },
  {
   "id": "open-to-work",
   "group": "Open to Work",
   "title": "Open to Work, recruiters only",
   "open": "https://www.linkedin.com/in/jordan-avery-example/",
   "hint": "Click Open to, then Finding a new job. Copy in the values below, set who can see it to Recruiters only, and save.",
   "copy": [
    {
     "label": "Job titles",
     "text": "Reporting Analyst\nData Analyst\nBusiness Intelligence Analyst"
    },
    {
     "label": "Locations",
     "text": "Melbourne, Victoria, Australia"
    },
    {
     "label": "Workplace",
     "text": "Hybrid, On-site"
    },
    {
     "label": "Job types",
     "text": "Full-time"
    }
   ]
  }
 ]
};
