import type { SkillCategory, SkillDef } from "./index";

// Compact table: [canonical name, category, aliases separated by "|", implied parents separated by "|"].
// Aliases are lower case and matched on word boundaries where + and # count as word characters.
// Ambiguous short names (Go, R, C, Excel, React, Swift, Spark, Word) only match unambiguous forms.
type Row = [string, SkillCategory, string?, string?];

const ROWS: Row[] = [
  // Data and analytics
  ["SQL", "data", "t-sql|tsql|pl/sql|plsql|structured query language"],
  ["Power BI", "analytics", "powerbi|power bi desktop|pbi"],
  ["DAX", "analytics", "dax formulas", "Power BI"],
  ["Power Query", "analytics", "m query", "Excel"],
  ["Tableau", "analytics", "tableau desktop|tableau server"],
  ["Looker", "analytics", "looker studio|google data studio|lookml"],
  ["Qlik", "analytics", "qlikview|qlik sense"],
  ["Excel", "office", "microsoft excel|ms excel|advanced excel|excel modelling|excel modeling|spreadsheets"],
  ["VBA", "office", "excel vba|macros", "Excel"],
  ["Pivot tables", "office", "pivottables|pivot table", "Excel"],
  ["Python", "language", "python3|python 3"],
  ["pandas", "data", "pandas library", "Python"],
  ["NumPy", "data", "numpy", "Python"],
  ["scikit-learn", "data", "sklearn|scikit learn", "Python"],
  ["R", "language", "r programming|rstudio|r studio|tidyverse|ggplot2"],
  ["Statistics", "data", "statistical analysis|statistical modelling|statistical modeling|regression analysis|hypothesis testing"],
  ["A/B testing", "data", "ab testing|a/b tests|split testing|experimentation"],
  ["Machine learning", "data", "ml models|predictive modelling|predictive modeling"],
  ["dbt", "data", "data build tool|dbt core|dbt cloud"],
  ["Snowflake", "data", "snowflake data cloud"],
  ["Databricks", "data", "databricks lakehouse"],
  ["Apache Spark", "data", "pyspark|spark sql|apache spark"],
  ["Airflow", "data", "apache airflow"],
  ["ETL", "data", "elt|etl pipelines|data pipelines|data pipeline"],
  ["Data modelling", "data", "data modeling|dimensional modelling|dimensional modeling|star schema"],
  ["Data warehousing", "data", "data warehouse|data warehouses"],
  ["Data validation", "data", "data quality|data accuracy checks|data cleansing|data cleaning"],
  ["Data visualisation", "analytics", "data visualization|dashboards|dashboard design|dashboarding"],
  ["KPI reporting", "analytics", "kpi tracking|kpis|kpi dashboards|performance reporting"],
  ["Reconciliation", "data", "reconciliations|account reconciliation"],
  ["SAS", "data", "sas enterprise guide"],
  ["SPSS", "data", "ibm spss"],
  ["Google Analytics", "analytics", "ga4|google analytics 4|universal analytics"],
  ["Alteryx", "data", "alteryx designer"],
  ["SSIS", "data", "sql server integration services"],
  ["SSRS", "analytics", "sql server reporting services"],
  // Languages
  ["JavaScript", "language", "javascript|ecmascript|es6"],
  ["TypeScript", "language", "typescript"],
  ["Java", "language", "java 8|java 11|java 17|core java"],
  ["C#", "language", "c#|csharp|c sharp"],
  ["C++", "language", "c++|cpp"],
  ["Go", "language", "golang|go programming|go language"],
  ["Rust", "language", "rust programming|rustlang"],
  ["Kotlin", "language", "kotlin"],
  ["Swift", "language", "swiftui|swift programming|ios swift"],
  ["PHP", "language", "php 8|php7"],
  ["Ruby", "language", "ruby on rails"],
  ["Scala", "language", "scala"],
  ["Bash", "language", "shell scripting|bash scripting|shell scripts"],
  ["PowerShell", "language", "powershell scripting"],
  ["HTML", "web", "html5"],
  ["CSS", "web", "css3|sass|scss|tailwind|tailwind css"],
  // Web and APIs
  ["React", "web", "react.js|reactjs|react js|react native|react hooks"],
  ["Next.js", "web", "nextjs|next js", "React"],
  ["Node.js", "web", "nodejs|node js|express.js|expressjs", "JavaScript"],
  ["Angular", "web", "angularjs|angular 2+"],
  ["Vue", "web", "vue.js|vuejs|nuxt"],
  ["Django", "web", "django rest framework", "Python"],
  ["Flask", "web", "flask api", "Python"],
  ["FastAPI", "web", "fastapi", "Python"],
  [".NET", "web", "dotnet|asp.net|.net core|.net framework", "C#"],
  ["Spring Boot", "web", "spring framework|spring boot", "Java"],
  ["REST APIs", "web", "rest api|restful|restful apis|api integration|api integrations|apis"],
  ["GraphQL", "web", "graphql"],
  ["Microservices", "web", "microservice architecture|microservices architecture"],
  ["Git", "devops", "github|gitlab|bitbucket|version control"],
  ["Unit testing", "devops", "jest|pytest|junit|vitest|test automation|automated testing"],
  ["Playwright", "devops", "playwright", "Unit testing"],
  ["Cypress", "devops", "cypress.io", "Unit testing"],
  ["Selenium", "devops", "selenium webdriver", "Unit testing"],
  // Databases
  ["PostgreSQL", "data", "postgres|postgresql", "SQL"],
  ["MySQL", "data", "mysql|mariadb", "SQL"],
  ["SQL Server", "data", "ms sql|mssql|microsoft sql server", "SQL"],
  ["Oracle", "data", "oracle database|oracle db", "SQL"],
  ["MongoDB", "data", "mongo|mongodb atlas"],
  ["DynamoDB", "cloud", "amazon dynamodb|dynamo db", "AWS"],
  ["Redis", "data", "redis cache"],
  ["Elasticsearch", "data", "elastic search|opensearch|elk stack"],
  ["Supabase", "data", "supabase"],
  ["BigQuery", "cloud", "google bigquery", "GCP"],
  ["Redshift", "cloud", "amazon redshift", "AWS"],
  // Cloud
  ["AWS", "cloud", "amazon web services|aws cloud"],
  ["AWS Lambda", "cloud", "lambda functions|aws lambda|lambda", "AWS"],
  ["API Gateway", "cloud", "amazon api gateway|aws api gateway", "AWS"],
  ["Amazon S3", "cloud", "aws s3|s3 buckets", "AWS"],
  ["Amazon EC2", "cloud", "aws ec2|ec2 instances", "AWS"],
  ["IAM", "security", "aws iam|identity and access management|least privilege"],
  ["CloudWatch", "cloud", "amazon cloudwatch|aws cloudwatch", "AWS"],
  ["CloudTrail", "cloud", "aws cloudtrail", "AWS"],
  ["CloudFormation", "devops", "aws cloudformation|aws cdk|cdk", "AWS"],
  ["Amazon Connect", "crm", "aws connect|amazon connect contact centre|amazon connect contact center", "AWS"],
  ["Step Functions", "cloud", "aws step functions", "AWS"],
  ["ECS", "cloud", "amazon ecs|fargate|aws fargate", "AWS"],
  ["EKS", "cloud", "amazon eks", "AWS"],
  ["AWS Glue", "cloud", "glue jobs|aws glue", "AWS"],
  ["Azure", "cloud", "microsoft azure|azure cloud"],
  ["Azure Functions", "cloud", "azure functions", "Azure"],
  ["Azure DevOps", "devops", "azure pipelines", "Azure"],
  ["Entra ID", "security", "azure ad|azure active directory|entra"],
  ["Azure Data Factory", "data", "adf|data factory", "Azure"],
  ["Synapse", "data", "azure synapse", "Azure"],
  ["Microsoft Fabric", "data", "fabric lakehouse"],
  ["GCP", "cloud", "google cloud|google cloud platform"],
  ["Firebase", "cloud", "firebase", "GCP"],
  ["Vercel", "cloud", "vercel"],
  // DevOps and infrastructure
  ["Terraform", "devops", "terraform|hcl|opentofu"],
  ["Docker", "devops", "docker|containerisation|containerization|docker compose"],
  ["Kubernetes", "devops", "k8s|kubernetes|helm"],
  ["CI/CD", "devops", "ci cd|continuous integration|continuous delivery|continuous deployment|build pipelines"],
  ["GitHub Actions", "devops", "gh actions|github workflows", "CI/CD"],
  ["Jenkins", "devops", "jenkins pipelines", "CI/CD"],
  ["Ansible", "devops", "ansible playbooks"],
  ["Linux", "devops", "ubuntu|red hat|rhel|centos|unix"],
  ["Windows Server", "devops", "windows server 2019|windows server 2022"],
  ["Computer networking", "devops", "tcp/ip|dns|dhcp|vpn|lan|wan|routing and switching|network administration|cisco"],
  ["Active Directory", "security", "ad ds|group policy|gpo"],
  ["Microsoft Intune", "devops", "intune|endpoint manager"],
  ["VMware", "devops", "vsphere|esxi"],
  ["Observability", "devops", "datadog|new relic|grafana|prometheus|application monitoring"],
  ["Infrastructure as code", "devops", "iac|infrastructure-as-code"],
  // Security
  ["Cyber security", "security", "cybersecurity|information security|infosec"],
  ["SIEM", "security", "security information and event management|sentinel|microsoft sentinel|qradar"],
  ["Splunk", "security", "splunk enterprise", "SIEM"],
  ["ISO 27001", "security", "iso27001|iso/iec 27001"],
  ["Essential Eight", "security", "essential 8|acsc essential eight"],
  ["NIST", "security", "nist csf|nist 800-53|nist sp 800-171"],
  ["Vulnerability management", "security", "vulnerability scanning|penetration testing|pen testing|nessus"],
  ["Incident response", "security", "security incident response|incident handling"],
  ["Identity management", "security", "okta|sso|single sign on|mfa|multi factor authentication"],
  ["Risk management", "domain", "risk assessments|risk assessment|risk registers"],
  ["Compliance", "domain", "regulatory compliance|audit compliance|governance risk and compliance|grc"],
  // ITSM, CRM and contact centre
  ["ServiceNow", "crm", "service now|servicenow itsm"],
  ["Jira", "crm", "jira software|jira service management|jsm"],
  ["Confluence", "crm", "atlassian confluence"],
  ["Zendesk", "crm", "zendesk support"],
  ["Freshdesk", "crm", "freshservice|freshworks"],
  ["HaloPSA", "crm", "halo psa|haloitsm"],
  ["ConnectWise", "crm", "connectwise manage|connectwise psa"],
  ["Salesforce", "crm", "salesforce crm|sfdc|service cloud|sales cloud"],
  ["HubSpot", "crm", "hubspot crm"],
  ["Dynamics 365", "crm", "microsoft dynamics|dynamics crm|d365"],
  ["Genesys", "crm", "genesys cloud|genesys purecloud"],
  ["Contact flows", "crm", "contact flow|call flows|call routing|routing profiles|ivr|interactive voice response"],
  ["Workforce management", "domain", "wfm|rostering|scheduling and forecasting"],
  ["CSAT", "domain", "customer satisfaction|csat scores"],
  ["NPS", "domain", "net promoter score"],
  ["AHT", "domain", "average handle time|average handling time"],
  ["SLA reporting", "domain", "slas|service level agreements|service levels|sla management"],
  ["ITIL", "method", "itil v4|itil foundation|itil 4"],
  ["Technical support", "domain", "it support|level 1 support|level 2 support|l1 support|l2 support|service desk|help desk|helpdesk|desktop support"],
  ["Customer service", "domain", "customer support|client service|customer care"],
  ["Complaint handling", "domain", "complaints management|complaint resolution"],
  ["Escalation management", "domain", "escalations"],
  // Office and collaboration
  ["Microsoft 365", "office", "office 365|o365|m365|microsoft office|ms office"],
  ["Microsoft Word", "office", "ms word|microsoft word"],
  ["PowerPoint", "office", "microsoft powerpoint|ms powerpoint"],
  ["SharePoint", "office", "sharepoint online"],
  ["Microsoft Teams", "office", "ms teams|microsoft teams"],
  ["Google Workspace", "office", "g suite|gsuite|google sheets|google docs"],
  ["Power Automate", "office", "microsoft flow|power automate"],
  ["Power Apps", "office", "powerapps|power apps"],
  // Finance
  ["Xero", "domain", "xero accounting"],
  ["MYOB", "domain", "myob accountright"],
  ["SAP", "domain", "sap s/4hana|s/4hana|sap erp|sap fico"],
  ["NetSuite", "domain", "oracle netsuite"],
  ["Accounts payable", "domain", "ap processing|creditors"],
  ["Accounts receivable", "domain", "ar processing|debtors|debt collection"],
  ["Payroll", "domain", "payroll processing"],
  ["Financial modelling", "domain", "financial modeling|financial models"],
  ["Budgeting", "domain", "budgets|forecasting and budgeting|financial forecasting"],
  ["Financial reporting", "domain", "management accounts|month end|month-end|end of month reporting"],
  ["BAS", "domain", "bas lodgement|gst returns"],
  ["Auditing", "domain", "internal audit|external audit|audit and assurance"],
  // Marketing and content
  ["SEO", "domain", "search engine optimisation|search engine optimization"],
  ["SEM", "domain", "search engine marketing|paid search|ppc"],
  ["Google Ads", "domain", "google adwords|adwords", "SEM"],
  ["Meta Ads", "domain", "facebook ads|instagram ads|meta business suite"],
  ["LinkedIn Ads", "domain", "linkedin campaign manager"],
  ["Email marketing", "domain", "email campaigns|mailchimp|klaviyo|marketing automation"],
  ["Content strategy", "domain", "content marketing|content plans|editorial calendar"],
  ["Copywriting", "domain", "copy writing|copywriter"],
  ["Social media", "domain", "social media marketing|social media management"],
  ["CRM marketing", "domain", "lifecycle marketing|retention marketing"],
  ["WordPress", "web", "wordpress"],
  ["Shopify", "web", "shopify"],
  // Design and product
  ["Figma", "design", "figma"],
  ["Adobe Creative Suite", "design", "photoshop|illustrator|indesign|adobe xd|creative cloud"],
  ["UX research", "design", "user research|usability testing|user interviews"],
  ["Wireframing", "design", "wireframes|prototyping|prototypes"],
  ["Design systems", "design", "design system|component libraries"],
  ["Accessibility", "design", "wcag|a11y|web accessibility"],
  ["Product management", "product", "product owner|product roadmap|product roadmaps|product strategy"],
  ["User stories", "product", "user story|acceptance criteria|backlog grooming|backlog refinement"],
  ["Requirements gathering", "product", "requirements elicitation|business requirements|functional requirements"],
  ["Process mapping", "product", "bpmn|process modelling|process modeling|visio"],
  ["Stakeholder management", "product", "stakeholder engagement|stakeholder communication|stakeholder reporting"],
  ["Process improvement", "method", "continuous improvement|process optimisation|process optimization|business process improvement"],
  ["Change management", "method", "organisational change|organizational change|prosci"],
  // Methods
  ["Agile", "method", "agile delivery|agile methodologies|agile methodology"],
  ["Scrum", "method", "scrum master|sprint planning|sprints", "Agile"],
  ["Kanban", "method", "kanban boards", "Agile"],
  ["Prince2", "method", "prince 2|prince2 foundation"],
  ["PMP", "method", "pmbok|project management professional"],
  ["Project management", "method", "project delivery|project coordination|project planning"],
  ["Lean", "method", "lean methodology|lean principles"],
  ["Six Sigma", "method", "lean six sigma|green belt|black belt"],
  ["Waterfall", "method", "waterfall methodology"],
  // People, HR and operations
  ["Recruitment", "domain", "talent acquisition|sourcing candidates|full cycle recruitment|end to end recruitment"],
  ["Onboarding", "domain", "employee onboarding|induction"],
  ["Employee relations", "domain", "industrial relations|workplace relations"],
  ["Workday", "domain", "workday hcm"],
  ["HRIS", "domain", "human resources information system"],
  ["Training delivery", "domain", "training sessions|staff training|delivered training|facilitation|workshops"],
  ["Team leadership", "domain", "people leadership|team leader|managed a team|people management|line management"],
  ["Coaching", "domain", "mentoring|performance coaching"],
  ["Inventory management", "domain", "stock control|inventory control"],
  ["Supply chain", "domain", "supply chain management|procurement|purchasing"],
  ["Logistics", "domain", "freight|warehousing|distribution centre|distribution center"],
  ["Operations management", "domain", "business operations|operational management"],
  ["Vendor management", "domain", "supplier management|contract management"],
  ["B2B sales", "domain", "business development|new business|account management|b2b sales|sales targets|sales pipeline"],
  ["Negotiation", "domain", "contract negotiation"],
  ["Customer success", "domain", "client success|customer retention"],
  ["Documentation", "domain", "technical writing|user guides|knowledge base articles|process documentation"],
  // Healthcare and education administration
  ["Medical terminology", "domain", "clinical terminology"],
  ["Patient administration", "domain", "patient bookings|medical reception|patient records"],
  ["Medicare billing", "domain", "medicare|bulk billing"],
  ["Curriculum design", "domain", "curriculum development|instructional design|learning design"],
  ["LMS", "domain", "learning management system|moodle|canvas lms"],
  // AI
  ["LLMs", "data", "large language models|llm|generative ai|genai|prompt engineering"],
  ["OpenAI API", "data", "openai|chatgpt api|gpt-4", "LLMs"],
  ["Claude API", "data", "anthropic api|claude api", "LLMs"],
  ["RAG", "data", "retrieval augmented generation", "LLMs"],
  // Tools that show up often in adverts
  ["Jupyter", "data", "jupyter notebooks|jupyterlab", "Python"],
  ["Matplotlib", "data", "seaborn|plotly", "Python"],
  ["Kafka", "data", "apache kafka|event streaming"],
  ["Hadoop", "data", "hdfs|hive"],
  ["Fivetran", "data", "fivetran"],
  ["Metabase", "analytics", "metabase"],
  ["Data governance", "data", "data stewardship|master data management|mdm|data catalogue|data catalog"],
  ["Azure SQL", "data", "azure sql database", "Azure"],
  ["Cosmos DB", "data", "azure cosmos db", "Azure"],
  ["Postman", "web", "postman"],
  ["OpenAPI", "web", "swagger|openapi spec"],
  ["Redux", "web", "redux toolkit", "React"],
  ["Storybook", "web", "storybook"],
  ["Nginx", "devops", "nginx"],
  ["Cloudflare", "cloud", "cloudflare workers"],
  ["Sentry", "devops", "sentry.io"],
  ["Zapier", "office", "zapier automations|make.com|integromat"],
  ["Notion", "office", "notion workspace"],
  ["Asana", "office", "asana"],
  ["Monday.com", "office", "monday com"],
  ["Trello", "office", "trello boards"],
  ["Miro", "design", "miro boards"],
  ["Smartsheet", "office", "smartsheet"],
];

// Names that are also common English words only match with their capitalisation.
const CASE_SENSITIVE = new Set(["Swift", "Rust", "Kotlin", "Scala", "Java", "Ruby", "Excel", "React", "Lean", "BAS", "Oracle"]);
// Names too short to match safely on their own ("R&D", "go live"). Only their aliases match.
const ALIAS_ONLY = new Set(["R", "Go"]);

export const SKILL_DEFS: SkillDef[] = ROWS.map(([name, category, aliases, implies]) => ({
  name,
  category,
  aliases: (aliases ?? "").split("|").filter(Boolean),
  ...(implies ? { implies: implies.split("|").filter(Boolean) } : {}),
  ...(CASE_SENSITIVE.has(name) ? { caseSensitive: true } : {}),
  ...(ALIAS_ONLY.has(name) ? { aliasOnly: true } : {}),
}));
