// One concrete, honest next step per skill. Named resources are free or official.
export const LEARN: Record<string, string> = {
  SQL: "Work through SQLBolt or the Mode SQL tutorial, then answer three real questions from a public dataset.",
  "Power BI": "Complete the Microsoft Learn PL-300 learning path and publish one report built on public data.",
  DAX: "Follow the DAX section of the Microsoft Learn PL-300 path and rebuild three measures from your own report.",
  Tableau: "Use Tableau Public with its free training videos and publish one dashboard to your profile.",
  Excel: "Take Microsoft Learn's Excel modules on lookups and pivot tables, then rebuild a report you produce by hand.",
  "Power Query": "Follow Microsoft's Power Query documentation tutorials and automate one manual clean up you do today.",
  Python: "Finish the official Python tutorial at python.org, then automate one repetitive task from your current work.",
  pandas: "Work through the pandas getting started tutorials and reproduce one of your Excel analyses in a notebook.",
  Statistics: "Take Khan Academy's statistics and probability course and apply one test to a dataset you know.",
  "A/B testing": "Read the free Udacity A/B testing course notes and design a test for a change you have seen made.",
  dbt: "Complete dbt Fundamentals on dbt Learn, which is free, and model one small public dataset.",
  Snowflake: "Use a Snowflake free trial with the Zero to Snowflake quickstart.",
  Databricks: "Use Databricks Free Edition and its getting started notebooks.",
  Airflow: "Follow the Apache Airflow official tutorial and schedule one small pipeline locally.",
  "Machine learning": "Take the free Google Machine Learning Crash Course and train one model on a public dataset.",
  JavaScript: "Work through the MDN JavaScript guide and build one small interactive page.",
  TypeScript: "Read the official TypeScript Handbook and convert one small JavaScript project.",
  React: "Do the official tutorial at react.dev and ship one small app with real data.",
  "Next.js": "Complete the free Next.js Learn course on nextjs.org.",
  "Node.js": "Follow the Node.js official learn guides and build one small REST API.",
  "REST APIs": "Build a small API and document it, using the MDN HTTP guide as reference.",
  Git: "Work through the free Pro Git book chapters one to three and keep a project on GitHub.",
  "Unit testing": "Add tests to one existing project using the official docs for Jest, Vitest or pytest.",
  Java: "Follow the dev.java learning path and build one small command line app.",
  "C#": "Complete Microsoft Learn's C# fundamentals path.",
  AWS: "Take AWS Skill Builder's free Cloud Practitioner Essentials course.",
  "AWS Lambda": "Follow the AWS Lambda getting started guide and deploy one function on the free tier.",
  DynamoDB: "Follow the DynamoDB getting started guide and model one small application's data.",
  IAM: "Read the AWS IAM best practices guide and audit the permissions on a test account.",
  CloudWatch: "Set up CloudWatch alarms and a dashboard for a free tier resource using the AWS guide.",
  CloudFormation: "Deploy one stack with the AWS CloudFormation getting started guide.",
  "Amazon Connect": "Build a test contact centre with the Amazon Connect administrator guide and its free tier.",
  Azure: "Complete Microsoft Learn's AZ-900 Azure Fundamentals path.",
  GCP: "Take Google Cloud Skills Boost's free introductory labs.",
  Terraform: "Follow the HashiCorp Terraform get started tutorials and manage one real resource.",
  Docker: "Work through the Docker getting started guide and containerise one of your projects.",
  Kubernetes: "Use the Kubernetes Basics tutorial on kubernetes.io with a local cluster.",
  "CI/CD": "Add a build and test pipeline to one repository with GitHub Actions.",
  "GitHub Actions": "Follow GitHub's Actions quickstart and add tests to a workflow.",
  Linux: "Work through the Linux Foundation's free Introduction to Linux course.",
  "Cyber security": "Take the free ACSC Essential Eight overview and Cisco Networking Academy's Introduction to Cybersecurity.",
  SIEM: "Use Splunk's free Splunk Fundamentals training and search sample logs.",
  Splunk: "Complete Splunk's free Fundamentals 1 course.",
  "Essential Eight": "Read the ACSC Essential Eight maturity model and map one environment you know against it.",
  "ISO 27001": "Read an ISO 27001 controls overview and draft one policy against a control.",
  ServiceNow: "Use the ServiceNow Developer Program's free personal instance and its learning paths.",
  Jira: "Use Atlassian University's free Jira fundamentals courses on a free site.",
  Salesforce: "Complete the free Salesforce Trailhead Admin Beginner trail.",
  HubSpot: "Take a free HubSpot Academy certification course.",
  ITIL: "Read an ITIL 4 Foundation summary and map one service you supported to the practices.",
  "Google Analytics": "Complete Google Analytics Academy courses on Skillshop, which are free.",
  "Google Ads": "Complete the free Google Ads certifications on Skillshop.",
  SEO: "Work through Google Search Central's SEO starter guide and audit one site.",
  Figma: "Follow Figma's free Learn Design courses and redesign one screen you use daily.",
  "UX research": "Run three short usability tests on a product you use and write up the findings.",
  Agile: "Read the Scrum Guide and the Agile Manifesto, then run a two week personal project in sprints.",
  Scrum: "Read the official Scrum Guide and take Scrum.org's free open assessment.",
  "Project management": "Take Google's project management course on Coursera with financial aid or audit the free modules.",
  Prince2: "Read a PRINCE2 Foundation summary and plan one small project with its stages.",
  "Process improvement": "Map one process you know end to end and identify the step that wastes the most time.",
  "Stakeholder management": "Build a stakeholder map for a current piece of work and agree update cadences.",
  "Requirements gathering": "Write user stories with acceptance criteria for a feature you would change.",
  Xero: "Complete Xero's free Xero Advisor certification.",
  MYOB: "Use MYOB's free education resources and a trial file.",
  "Power Automate": "Follow Microsoft Learn's Power Automate path and automate one email or file task.",
  LLMs: "Read Anthropic's prompt engineering guide and build one small tool that calls a model API.",
};
