// Banned generic phrasing for generated application documents.
//
// Some entries are adapted from the humanizer scrub rules in linkedin-skills by Serge Bulaev,
// MIT License, https://github.com/sergebulaev/linkedin-skills
// (skills/linkedin-humanizer/references/scrub-rules.md). Copyright (c) 2026 Sergey Bulaev.
// Those entries are marked "humanizer". The rest are our own.
//
// Entries are lower case regular expression sources, matched case insensitively on word boundaries.

export const AI_PHRASES: readonly string[] = [
  // Our own list, from the product text rules.
  "i am excited to",
  "i'm excited to",
  "excited to",
  "thrilled",
  "passionate about",
  "passion for",
  "leverag(?:e|es|ed|ing)",
  "delv(?:e|es|ed|ing)",
  "in today's fast[- ]paced",
  "fast[- ]paced (?:world|environment)",
  "proven track record",
  "dynamic",
  "synerg(?:y|ies|istic)",
  "spearhead(?:s|ed|ing)?",
  "seamless(?:ly)?",
  "robust",
  "cutting[- ]edge",
  "game[- ]chang(?:er|ers|ing)",
  "unlock(?:s|ed|ing)?",
  "elevat(?:e|es|ed|ing)",
  "embark(?:s|ed|ing)?",
  "journey",
  "testament",
  "i hope this finds you well",
  "i am writing to express my interest",
  "ideal candidate",
  "perfect fit",
  "results[- ]driven",
  "go[- ]getter",
  "team player",
  "hit the ground running",
  "think outside the box",
  "go the extra mile",
  "wear many hats",
  "world[- ]class",
  "state[- ]of[- ]the[- ]art",
  "best[- ]in[- ]class",
  "revolutioni[sz](?:e|es|ed|ing)",
  "transformative",
  "ever[- ]evolving",
  "a myriad of",
  "plethora",
  "it is worth noting",
  "it's worth noting",
  "it is important to note",
  "eager to",
  "delighted to",
  "humbled",
  // humanizer, phrase level cleanup and strict vocabulary.
  "in the age of ai",
  "at the end of the day",
  "deep dive",
  "move the needle",
  "needle[- ]moving",
  "paradigm shift",
  "pivotal moment",
  "tapestry",
  "in a world where",
  "let that sink in",
  "that's the real story",
  "multifaceted",
  "holistic",
  "harness(?:es|ed|ing)?",
  "empower(?:s|ed|ing|ment)?",
  "utili[sz](?:e|es|ed|ing)",
  "realm",
  // humanizer, outline closers and announcement openers.
  "in conclusion",
  "to summari[sz]e",
  "in summary",
  "looking ahead",
  "i'm thrilled to share",
  "excited to announce",
  "honou?red to be",
];

// Meta commentary and AI disclosure. "generated" is handled separately in the linter because
// "Generated $2M in sales" is a legitimate CV line.
export const META_PHRASES: readonly string[] = [
  "as an ai",
  "as a language model",
  "language model",
  "here is your",
  "here's your",
  "i hope this",
  "this letter",
  "this cover letter",
  "below is",
  "as requested",
  "i have written",
  "i've written",
  "i have drafted",
  "ai[- ]generated",
  "as of my last update",
  "knowledge cutoff",
  "chatgpt",
];
