import { describe, expect, it } from "vitest";
import type { DraftDocument } from "@/lib/types";
import { lintDocument, lintText } from "./lint";

const rules = (text: string, opts?: Parameters<typeof lintText>[1]) => lintText(text, opts).map((i) => i.rule);

describe("lintText", () => {
  it("passes plain recruiter prose", () => {
    expect(lintText("I built a Power BI dashboard used by regional managers.")).toEqual([]);
  });

  it("flags em dashes, en dashes, double hyphens and spaced hyphens", () => {
    expect(rules("Built it — fast")).toEqual(["dash"]);
    expect(rules("Built it – fast")).toEqual(["dash"]);
    expect(rules("Built it -- fast")).toEqual(["dash"]);
    expect(rules("Built it - fast")).toEqual(["dash"]);
    expect(rules("Full-stack T-SQL work in 2019-2021")).toEqual([]);
  });

  it("flags semicolons, double spaces, bold and emoji as errors", () => {
    expect(lintText("One; two")[0]).toMatchObject({ rule: "semicolon", severity: "error" });
    expect(rules("One  two")).toEqual(["double-space"]);
    expect(rules("A **bold** claim")).toEqual(["bold"]);
    expect(rules("A __bold__ claim")).toEqual(["bold"]);
    expect(lintText("Great work \u{1F680}")[0]).toMatchObject({ rule: "emoji", severity: "error" });
    expect(rules("Microsoft® Excel™")).toEqual([]);
  });

  it("warns on exclamation marks", () => {
    expect(lintText("Hello there!")).toEqual([
      expect.objectContaining({ rule: "exclamation", severity: "warning" }),
    ]);
  });

  it("flags connector colons but not urls, emails or times", () => {
    expect(rules("Key result: faster reports")).toEqual(["colon"]);
    expect(rules("See https://example.com/work or jordan.avery@example.com at 9:30")).toEqual([]);
  });

  it("flags generic AI phrases case insensitively", () => {
    const issues = lintText("I am Excited To apply and LEVERAGED a Robust, cutting edge journey.");
    expect(issues.filter((i) => i.rule === "ai-phrase").map((i) => i.excerpt.length > 0)).toHaveLength(5);
    expect(issues.every((i) => i.severity === "error")).toBe(true);
    expect(rules("A dynamic team with a proven track record")).toEqual(["ai-phrase", "ai-phrase"]);
  });

  it("does not flag words that merely contain a banned stem", () => {
    expect(rules("Used a leverage ratio model")).toEqual(["ai-phrase"]);
    expect(rules("Handled journeyman tasks and unlocking keys")).toEqual(["ai-phrase"]);
    expect(rules("Handled journeyman tasks")).toEqual([]);
  });

  it("flags meta commentary and AI disclosure", () => {
    expect(rules("As an AI, here is your letter")).toEqual(["meta", "meta"]);
    expect(rules("I hope this helps")).toEqual(["meta"]);
    expect(rules("This was generated for you")).toEqual(["meta"]);
    expect(rules("Text generated by a language model")).toEqual(["meta", "meta"]);
    expect(rules("Generated $2M in new sales")).toEqual([]);
    expect(rules("Generated 40 qualified leads a month")).toEqual([]);
  });

  it("checks numbers only when an allow list is given", () => {
    expect(rules("Cut costs by 30% in 2 years")).toEqual([]);
    const allowed = new Set(["30"]);
    const issues = lintText("Cut costs by 30% in 2 years", { allowedNumbers: allowed });
    expect(issues).toEqual([expect.objectContaining({ rule: "number", severity: "error" })]);
    expect(issues[0].message).toContain("2");
    expect(rules("Managed 1,200 sites", { allowedNumbers: new Set(["1200"]) })).toEqual([]);
    expect(rules("Call 0400 000 123", { allowedNumbers: new Set() })).toEqual([]);
  });

  it("flags placeholders unless allowed", () => {
    expect(rules("Hi [Name],")).toEqual(["placeholder"]);
    expect(rules("Hi [Name],", { allowPlaceholders: true })).toEqual([]);
  });

  it("tags the document kind and keeps an excerpt", () => {
    const [issue] = lintText("A very long sentence that goes on; and on", { doc: "cover_letter" });
    expect(issue.doc).toBe("cover_letter");
    expect(issue.excerpt).toContain(";");
  });
});

describe("lintDocument", () => {
  const doc: DraftDocument = {
    kind: "cv",
    title: "Jordan Avery CV",
    sections: [
      { heading: "Summary", style: "paragraph", items: [{ text: "Analyst — fast.", evidenceIds: ["E1"] }] },
      { heading: "Experience", style: "bullets", meta: "Analyst: Northwind", items: [] },
      { heading: "Skills; tools", style: "lines", items: [{ text: "SQL, Excel", evidenceIds: ["E2"] }] },
    ],
  };

  it("lints headings, meta and sentences and tags the doc", () => {
    const issues = lintDocument(doc);
    expect(issues.map((i) => i.rule).sort()).toEqual(["colon", "dash", "semicolon"]);
    expect(issues.every((i) => i.doc === "cv")).toBe(true);
  });

  it("passes number and placeholder options through", () => {
    const withNumbers: DraftDocument = {
      kind: "outreach",
      title: "Outreach",
      sections: [{ heading: "", style: "lines", items: [{ text: "Hi [Name], I cut costs 12%.", evidenceIds: ["E1"] }] }],
    };
    expect(lintDocument(withNumbers, { allowPlaceholders: true, allowedNumbers: new Set(["12"]) })).toEqual([]);
    expect(lintDocument(withNumbers, { allowedNumbers: new Set() }).map((i) => i.rule)).toEqual([
      "number",
      "placeholder",
    ]);
  });
});
