// Packs the LinkedIn Profile Filler extension with one person's plan. The extension code is the same for
// everyone. Only data.js changes, and it holds nothing but the approved text as a JSON value.
import JSZip from "jszip";
import type { FillPlan } from "./plan";

/** Shipped files, read from extension/linkedin-filler. The repo's demo data.js is never shipped. */
export const EXTENSION_FILES = [
  "manifest.json",
  "background.js",
  "panel.html",
  "panel.css",
  "panel.js",
  "filler.js",
  "icon16.png",
  "icon48.png",
  "icon128.png",
  "README.md",
] as const;
export type ExtensionFile = (typeof EXTENSION_FILES)[number];

export const FOLDER = "LinkedIn_Profile_Filler";

/**
 * data.js for one plan. JSON is valid JavaScript, so user text can only ever be string data. The escapes
 * keep it inert even if the file is pasted into an HTML page. No user text goes in the comment line.
 */
export function renderDataJs(plan: FillPlan): string {
  const json = JSON.stringify(plan, null, 1)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
  return `// Generated by JobsMarket. It holds only the profile text you approved and is read by panel.js.\nexport const PLAN = ${json};\n`;
}

/** The extension folder as a zip, ready for Load unpacked after it is extracted. */
export async function packExtension(files: ReadonlyMap<string, Uint8Array | string>, plan: FillPlan): Promise<Uint8Array> {
  const missing = EXTENSION_FILES.filter((name) => !files.has(name));
  if (missing.length) throw new Error(`Extension files missing: ${missing.join(", ")}`);
  const date = new Date(plan.createdAt);
  const zip = new JSZip();
  const dir = zip.folder(FOLDER);
  if (!dir) throw new Error("Could not create the extension folder in the zip.");
  for (const name of EXTENSION_FILES) dir.file(name, files.get(name) as Uint8Array | string, { date });
  dir.file("data.js", renderDataJs(plan), { date });
  return zip.generateAsync({ type: "uint8array", compression: "DEFLATE", platform: "UNIX" });
}
